### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by tonypee** [jayesbe/react-native-cacheable-image#23] opened 2016-11-10 11:08 UTC
I have implemented the <CacheableImage> then looking at the code a ReactiveImage is created with a url, and the files are created on my filesystem. But they just dont load. I have copied the uri, and put it in a normal Image, and still nothing. Is there anything i need to do to allow xcode to load images from file:// ? 

This doesnt work, but the url can be loaded in the browser:

<Image style={{ width: 100, height: 100 }} source={{uri:'file:///Users/tpee/Library/Developer/CoreSimulator/Devices/F80B7E6D-4339-44DE-9404-1D3F6DDB5D3E/data/Containers/Data/Application/EC6F28F6-8479-4BE5-9EEB-CEFFEF382117/Documents/snapcat.s3.amazonaws.com/654e6d0094674084bb91f11c5a3b4088e4b12f54'}} />

**Comment by jayesbe** [comment] 2016-11-10 11:28
@tonypee Unfortunately I am unsure of xcode issues because I don't have any way of testing iOS at the moment.  Could there be a permission issue? 

Have you followed the xcode instructions for react-native-fs https://github.com/johanneslumpe/react-native-fs ?

**Comment by jayesbe** [comment] 2016-11-10 11:53
@tonypee  Just realised you had the same issue with a standard React Image component. There definitely must be some type of file system permission issue with your app and xcode.

**Comment by jayesbe** [comment] 2016-11-10 11:53
Sorry.. will leave it open just in-case anyone can help. Will close it in a week otherwise.

**Comment by pvsousalima** [comment] 2016-11-14 01:22
I am also having the same issue as @tonypee :/
![simulator screen shot nov 13 2016 11 21 45 pm](https://cloud.githubusercontent.com/assets/1810178/20250640/fa2d8690-a9f7-11e6-9032-f5f17ba88aca.png)

The image above is a <Image> component. And the void space is the <CacheableImage> component which does not load any image 👎

**Comment by sir-gon** [comment] 2016-11-14 18:55
I have the same issue here.
I have react-native-fs previously working (because is dependency of another component).

I don't see any yellow warning or any console log neither

**Comment by pvsousalima** [comment] 2016-11-14 19:39
Why don't we move on dependencies? I used react-native-fetch-blob to fetch my images and AsyncStore to save the local path for my data 😄

**Comment by nbolender** [comment] 2016-11-16 06:24
Hey guys, it seems like this is caused by not specifying the file extension on iOS. I've been testing with this package and with the react-native Image component, and local images typically do not display if they don't have an extension.

Part of this seems to be due to UIImage's behavior where it expects local images without an extension to have a PNG extension – see the PNG note in [UIImage imageNamed's API Reference](https://developer.apple.com/reference/uikit/uiimage/1624146-imagenamed?language=objc).

I'm working on a PR that brings back the file extensions to cached images, which instantly made cached images work for me again.

**Comment by mynameisnoise** [comment] 2016-11-17 12:39
@nbolender, any updates?

**Comment by nbolender** [comment] 2016-11-17 18:19
@mynameisnoise I posted the PR above. Feel free to check it out and see if works for you. I also have two other PRs that may be of interest.

**Comment by mynameisnoise** [comment] 2016-11-18 13:55
@nbolender, yeah, that worked just fine! I had confirmation on both platforms.
Thank you, mate.

**Closed as completed** 2016-11-20 16:42 UTC

**Comment by DavitVosk** [comment] 2018-08-03 08:32
@nbolender I am trying to render an image from camera roll, but it does not show anything on the real device. On simulator it works as needed. Can you please help to understand what is a problem here. Thanks.

<Image style={{ width: 100, height: 100 }}
                     source={{uri:'file:///var/mobile/Media/DCIM/101APPLE/IMG_1861.PNG'}} />

**Comment by nbolender** [comment] 2018-08-13 18:48
@DavitVosk I think that may have something to do with sandboxing or camera roll permissions. I can't dig into it right now but you should poke around the react-native docs and maybe try using the built-in Image component to see if this is a problem with this library or something else.
