### ISSUE TITLE
React.createClass is not a function. (In 'React.createClass', 'React.createClass' is undefined)

### ISSUE THREAD

**Issue by lintelbeam** [jayesbe/react-native-cacheable-image#60] opened 2017-10-18 15:09 UTC
I have some trouble to use this module and I am getting error in react-native-response-image.js
My react native version is 0.49.3.
I think this module is not updated for latest react native version.
Could you kindly update this module?
Regards.[](url)
![simulator screen shot oct 18 2017 5 08 57 pm](https://user-images.githubusercontent.com/23495888/31726374-16ef1c0a-b427-11e7-8005-170abc4c28d8.png)

**Comment by hey-mx** [comment] 2017-11-15 21:48
Hi,

I have the same problem. @reactionic127 Did you fixed this issue?

**Comment by jorgeasolano** [comment] 2017-11-17 15:28
same issue here using  0.49.3

**Comment by rekliner** [comment] 2017-12-06 23:01
React 16 removed createClass.  This might help you: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactcreateclass

**Comment by jayesbe** [comment] 2017-12-07 15:14
Looks like the issue is with react-native-responsive-image.  master was using an old dep.. just merged an update to master that updates the dep that should fix this.

**Closed as completed by jayesbe** 2017-12-07 15:14 UTC
